# Generated by Django 5.1.1 on 2024-10-02 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worker', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customworker',
            name='is_staff',
        ),
        migrations.AlterField(
            model_name='customworker',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='customworker',
            name='mob',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='workerprofile',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='worker/profile_pic/'),
        ),
    ]
