# Generated by Django 5.1.1 on 2024-10-04 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worker', '0002_remove_customworker_is_staff_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customworker',
            name='is_staff',
            field=models.BooleanField(default=True),
        ),
    ]
