# Generated by Django 5.1.1 on 2024-10-13 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worker', '0005_remove_customworker_is_approved_customworker_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customworker',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
