# Generated by Django 5.1.1 on 2024-10-16 15:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worker', '0008_services_worker'),
    ]

    operations = [
        migrations.AlterField(
            model_name='services',
            name='worker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='worker.customworker'),
        ),
    ]
