# Generated by Django 5.1.1 on 2024-10-24 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worker', '0009_alter_services_worker'),
    ]

    operations = [
        migrations.AlterField(
            model_name='services',
            name='pic',
            field=models.FileField(blank=True, null=True, upload_to='services/'),
        ),
    ]
