# Generated by Django 5.1.1 on 2024-11-07 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worker', '0012_workerprofile_users_alter_requests_worker'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requests',
            name='status',
            field=models.CharField(choices=[('request_sent', 'Request Sent'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], default='request_sent', max_length=20),
        ),
    ]
