# Generated by Django 5.1.1 on 2024-11-08 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worker', '0014_requests_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='workerprofile',
            name='lat',
            field=models.DecimalField(decimal_places=20, default=1.2, max_digits=25),
        ),
        migrations.AddField(
            model_name='workerprofile',
            name='lng',
            field=models.DecimalField(decimal_places=20, default=1.2, max_digits=25),
        ),
        migrations.AddField(
            model_name='workerprofile',
            name='location',
            field=models.CharField(default='Kochi', max_length=255),
        ),
    ]
