# Generated by Django 5.1.1 on 2024-11-18 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worker', '0018_services_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='workerprofile',
            name='aadhaar_no',
            field=models.IntegerField(blank=True, max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='workerprofile',
            name='certificate',
            field=models.ImageField(blank=True, null=True, upload_to='worker/certificate/'),
        ),
        migrations.AddField(
            model_name='workerprofile',
            name='experience',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
