# Generated by Django 5.1.1 on 2024-11-18 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_auth', '0007_delete_services'),
        ('worker', '0019_workerprofile_aadhaar_no_workerprofile_certificate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workerprofile',
            name='services',
            field=models.ManyToManyField(blank=True, null=True, related_name='workers', to='admin_auth.categories'),
        ),
        migrations.AlterField(
            model_name='workerprofile',
            name='aadhaar_no',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
    ]
