# Generated by Django 5.1.1 on 2024-11-18 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_auth', '0007_delete_services'),
        ('worker', '0020_workerprofile_services_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workerprofile',
            name='services',
            field=models.ManyToManyField(related_name='workers', to='admin_auth.categories'),
        ),
    ]
