# Generated by Django 5.1.1 on 2024-11-18 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worker', '0021_alter_workerprofile_services'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workerprofile',
            name='first_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='workerprofile',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
