# Generated by Django 5.1.1 on 2024-11-21 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worker', '0022_alter_workerprofile_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requests',
            name='status',
            field=models.CharField(choices=[('request_sent', 'Request Sent'), ('accepted', 'Accepted'), ('completed', 'Completed'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], default='request_sent', max_length=20),
        ),
    ]
