# Generated by Django 5.1.1 on 2024-11-21 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worker', '0023_alter_requests_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='services',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
