# Generated by Django 5.1.1 on 2024-11-23 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worker', '0024_services_is_deleted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='services',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
