# Generated by Django 5.1.1 on 2024-12-19 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worker', '0028_workerprofile_is_subscribed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workerprofile',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
    ]
