# Generated by Django 5.1.1 on 2024-12-28 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worker', '0029_workerprofile_is_available'),
    ]

    operations = [
        migrations.AddField(
            model_name='workerprofile',
            name='stripe_customer_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
