# Generated by Django 5.1.1 on 2024-12-29 15:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worker', '0031_workerprofile_stripe_subscription_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('services_added', models.IntegerField(default=0)),
                ('services_updated', models.IntegerField(default=0)),
                ('user_requests_handled', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('worker_profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription_usage', to='worker.workerprofile')),
            ],
        ),
    ]
