# Generated by Django 5.1.1 on 2024-12-31 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worker', '0034_remove_workerprofile_stripe_subscription_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workersubscription',
            name='stripe_price_id',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='workersubscription',
            name='stripe_product_id',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
