# Generated by Django 5.1.1 on 2024-12-31 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worker', '0036_pendingworkersubscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='pendingworkersubscription',
            name='is_activated_now',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='workersubscription',
            name='invoice_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
