# Generated by Django 5.1.1 on 2024-12-31 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('worker', '0037_pendingworkersubscription_is_activated_now_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PendingWorkerSubscription',
        ),
    ]
