# Generated by Django 5.1.1 on 2025-01-03 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worker', '0038_delete_pendingworkersubscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='services',
            name='is_listed',
            field=models.BooleanField(default=True),
        ),
    ]
