# Generated by Django 5.1.1 on 2025-01-17 07:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worker', '0039_services_is_listed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='worker',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wallet', to='worker.customworker'),
        ),
    ]
