# Generated by Django 5.1.1 on 2024-10-14 22:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_auth', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categories',
            old_name='name',
            new_name='category_name',
        ),
        migrations.RenameField(
            model_name='services',
            old_name='name',
            new_name='service_name',
        ),
        migrations.RenameField(
            model_name='subcategories',
            old_name='name',
            new_name='subcategory_name',
        ),
    ]
