# Generated by Django 5.1.1 on 2024-10-15 00:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_auth', '0002_rename_name_categories_category_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='services',
            old_name='category_id',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='subcategories',
            old_name='category_id',
            new_name='category',
        ),
    ]
