# Generated by Django 5.1.1 on 2024-10-16 11:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_auth', '0003_rename_category_id_services_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='services',
            name='price',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='services',
            name='subcategory',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='services', to='admin_auth.subcategories'),
        ),
    ]
