# Generated by Django 5.1.1 on 2024-10-16 11:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_auth', '0004_services_price_services_subcategory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='services',
            name='price',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='services',
            name='subcategory',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='services', to='admin_auth.subcategories'),
        ),
    ]
