# Generated by Django 5.1.1 on 2024-10-16 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_auth', '0006_alter_services_subcategory'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Services',
        ),
    ]
