# Generated by Django 5.1.1 on 2024-12-12 05:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_auth', '0007_delete_services'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tier_name', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='SubscriptionFeatures',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform_fee_perc', models.IntegerField()),
                ('service_add_count', models.CharField(default='0', max_length=20)),
                ('service_update_count', models.CharField(default='0', max_length=20)),
                ('user_requests_count', models.CharField(default='0', max_length=20)),
                ('analytics', models.CharField(choices=[('no_analytics', 'No Analytics'), ('basic', 'Baisc'), ('advanced', 'Advanced')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscription_features', to='admin_auth.subscription')),
            ],
        ),
    ]
