# Generated by Django 5.1.1 on 2024-12-14 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_auth', '0008_subscription_subscriptionfeatures'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscriptionfeatures',
            old_name='service_add_count',
            new_name='service_add_limit',
        ),
        migrations.RenameField(
            model_name='subscriptionfeatures',
            old_name='service_update_count',
            new_name='service_update_limit',
        ),
        migrations.RenameField(
            model_name='subscriptionfeatures',
            old_name='user_requests_count',
            new_name='user_requests_limit',
        ),
        migrations.AlterField(
            model_name='subscriptionfeatures',
            name='analytics',
            field=models.CharField(choices=[('no_analytics', 'No Analytics'), ('basic', 'Basic'), ('advanced', 'Advanced')], default='no_analytics', max_length=20),
        ),
    ]
