# Generated by Django 5.1.1 on 2024-12-27 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_auth', '0010_subscription_analytics_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='stripe_price_id',
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='subscription',
            name='stripe_product_id',
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
    ]
