# Generated by Django 5.1.1 on 2024-11-11 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_userprofile_lat_alter_userprofile_lng_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='lat',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='lng',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='location',
        ),
        migrations.AddField(
            model_name='customuser',
            name='lat',
            field=models.DecimalField(decimal_places=20, max_digits=25, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='lng',
            field=models.DecimalField(decimal_places=20, max_digits=25, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='location',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
