# Generated by Django 5.1.1 on 2024-11-13 04:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_ordertracking'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordertracking',
            name='order',
        ),
        migrations.DeleteModel(
            name='Orders',
        ),
        migrations.DeleteModel(
            name='OrderTracking',
        ),
    ]
