# Generated by Django 5.1.1 on 2024-11-14 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_orders_ordertracking'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='user_description',
            field=models.TextField(null=True),
        ),
    ]
