# Generated by Django 5.1.1 on 2024-11-14 14:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_orders_user_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_amount', models.IntegerField()),
                ('status', models.CharField(choices=[('unPaid', 'UnPaid'), ('paid', 'Paid')], default='unPaid', max_length=20)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='order_payment', to='accounts.orders')),
            ],
        ),
        migrations.CreateModel(
            name='Additional_charges',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('price', models.IntegerField()),
                ('image', models.FileField(upload_to='users/payment/receipts/')),
                ('order_payment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='additional_charges', to='accounts.orderpayment')),
            ],
        ),
    ]
