# Generated by Django 5.1.1 on 2024-11-14 17:19

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_orderpayment_additional_charges'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderpayment',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='orderpayment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='additional_charges',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='users/payment/receipts/'),
        ),
        migrations.AlterField(
            model_name='additional_charges',
            name='order_payment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='additional_charges', to='accounts.orderpayment'),
        ),
    ]
