# Generated by Django 5.1.1 on 2024-11-21 14:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_orders_request'),
        ('worker', '0023_alter_requests_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='serviced_request', to='worker.requests'),
        ),
    ]
