# Generated by Django 5.1.1 on 2024-11-25 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0024_interactions'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Newtable',
        ),
    ]
