# Generated by Django 5.1.1 on 2024-12-02 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0027_alter_wallet_balance'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_id', models.IntegerField()),
                ('sender_type', models.CharField(choices=[('user', 'User'), ('worker', 'Worker')], max_length=10)),
                ('recipient_id', models.IntegerField()),
                ('recipient_type', models.CharField(choices=[('user', 'User'), ('worker', 'Worker')], max_length=10)),
                ('message', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
