# Generated by Django 5.1.1 on 2025-01-02 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0028_chatmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_any_pending_payment',
            field=models.BooleanField(default=False),
        ),
    ]
