# Generated by Django 5.1.1 on 2025-01-02 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0030_orders_worker_otp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='worker_otp',
            field=models.IntegerField(),
        ),
    ]
