# Generated by Django 5.1.1 on 2025-01-02 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0031_alter_orders_worker_otp'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orders',
            old_name='worker_otp',
            new_name='otp',
        ),
    ]
