# Generated by Django 5.1.1 on 2025-03-04 05:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0032_rename_worker_otp_orders_otp'),
        ('worker', '0040_alter_wallet_worker'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service', to='worker.services'),
        ),
    ]
